version: "3.8"
services:
  backend:
    image: backend:latest # nomeie a imagem da forma que desejar
    ports:
      - "5000:5000"
  # frontend:
  #   image: frontend:latest # nomeie a imagem da forma que desejar
  #   ports:
  #     - "3000:3000"
